<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Http;
use Illuminate\Http\Request;
use Intervention\Image\ImageManager;
use Storage;

class Landing extends Controller
{
    /**
     * Index method that display landing page
     */
    public function index()
    {
        $viewParameters = [
            "designList" => $this->requestDesignList()
        ];


        return view("landing/index", $viewParameters);
    }

    /** 
     * Request Design List from GET endpoint
     */
    private function requestDesignList()
    {
        try 
        {
            $response = Http::get('https://appdsapi-6aa0.kxcdn.com/content.php?lang=en&json=1&search_text=berlin&currencyiso=EUR');

            if ($response->ok())
            {
                $data = array_slice( $response->json()["content"], 0, 25);

                // Generate data to output
                $result = array();
                
                foreach ($data as $card)
                {
                    // Resize image
                    $thumbImage     = $this->downloadImage($card["thumb_url"]);
                    $encodedImage   = $this->resizeCardImage($thumbImage);

                    $entry = array(
                        "title"     => $card["title"],
                        "price"     => $card["price_foldingcard"],
                        "thumb"     => $encodedImage
                    );

                    $result[] = $entry;
                }


                return $result;
            }
        }
        catch(Exception $e)
        {
            return false;
        }
    }

    /**
     * Download an image from url and save to storage
     */
    private function downloadImage($url)
    {
        // Download image
        $contents   = file_get_contents($url);
        $name       = substr($url, strrpos($url, '/') + 1);
        $path       = 'cards/'. $name; 
        Storage::put($path, $contents);

        return $path;
    }

    /**
     * Return a base64 encoded image from path generated by downloadImage
     */
    private function resizeCardImage($path, $size=350)
    {
        $realPath = storage_path('app/' . $path);
        $manager = new ImageManager(array('driver' => 'gd'));
        $image = $manager->make($realPath)->resize($size, $size)->encode('data-url');

        return $image;
    }
}
